include:
 - project: devops/cicd-template
   file: "gitlab-ci-template.yml"

variables:
  CI_PROJECT_TYPE_FRONTEND: "TRUE"
  #CI_PROJECT_TYPE_BACKEND: "TRUE"
  #CI_PROJECT_MODE_MONO_REPO: "TRUE"
  #CI_PROJECT_MODE_MULTI_MODULE: "TRUE"
  #CI_APPLICATION_TYPE_MAVEN: "TRUE"
  #CI_APPLICATION_TYPE_GRADLE: "TRUE"
  #CI_RELEASE_TYPE_JIB: "TRUE"
  CI_RELEASE_TYPE_KANIKO: "TRUE"
