server:
  port: ${WU_API_SERVER_PORT:8690}
  servlet:
    application-display-name: wu-integration

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000
        loggerLevel: full
  httpclient:
    enabled: true
    disable-ssl-validation: true
  okhttp:
    enabled: false
logging:
  level:
    org:
      springframework:
        web: INFO
        ws:
          client:
            MessageTracing:
              sent: TRACE
              received: TRACE
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
